### ISSUE TITLE
[Python][RESOLVED] Websocket Connection, Authentication failed. Please check your api_key and api_secret.

### ISSUE THREAD

**Issue by a1q0** [bybit-exchange/api-connectors#29]
If you're having problem connecting through python, edit this file: https://github.com/bybit-exchange/api-connectors/blob/master/official-ws/python/BybitWebsocket.py

Go to line 86 and add a 1 in the "000" string like in the screen capture below

![cap](https://user-images.githubusercontent.com/1682540/75628134-7575ba00-5bd6-11ea-9748-0cb72819057a.PNG)

if you don't know where the file is located: https://www.google.com/search?q=pip+package+location

**Comment by dpuyosa** [comment]
You **should not** do that. As per de documentation:
```
// A UNIX timestamp after which the request become invalid. This is to prevent replay attacks.
// unit:millisecond
var expires = time.now()+1000;
```
Doing so, you are increasing the window by agreat amount, basically you are setting an infinite expiration date.


Here is an example of what you are doing:
In python, ``time``  works with seconds, the '000' is to make it milliseconds for the server.

 Mar 02, 2020 12:23:16 is **1583151796**
'1583151796' + '1000' -> **15831517961** minus '000' to keep it at seconds.
**15831517961** is 'Sep 06, 2471 03:52:41'

A better solution if your network is unreliable and you need a bigger window, increase the ``+1``
```
expires = str(int(round(time.time())+5))+'000'
```
This gives you 5 seconds to reach the server instead of the default 1.

**Comment by botbuildtra** [comment]
Neither one of the two fixes works right now for me. There seems to be no possibility to authenticate, even to testnet.

**Comment by Tinuz** [comment]
I am still getting this error. Anyone know if this error has been fixed? Or if there is a working workaround?

**Comment by dexter-2** [comment]
There are no problems with websocket authentication generally. You'd have to provide more details on your application so that we might find the problem. A common reason for encountering this error is because you're using the incorrect base endpoints for your API key. For instance, if you created the key on testnet.bybit.com but you're attempting to use it on the mainnet (with the `wss://stream.bybit.com/realtime` endpoint).

**Comment by dpuyosa** [comment]
> 
> 
> I am still getting this error. Anyone know if this error has been fixed? Or if there is a working workaround?

The error is on your end. Is you system clock synchronized?

**Comment by jonny07** [comment]
This error cost me hours of time and as others might also encounter it, here what I found:
For security, Bybit allows max 5s (min -1s) till a message that was sent from your PC is received by them.
=> In case your system clock is not in sync with Bybit, you will permanently get this error, because there will be a permanent time diff between the 2 clocks. The error will go away if you sync your system clock to correct time. Alternatively (and better), sync it to the Bybit time. Each request, you get in the return message "time now" back from Bybit, just set this as your time or use the special time endpoint from bybit. (To really ensure no problems, you should only set this time if it does not differ more than e.g. 0.5s from your current time. Otherwise in case of network delay of e.g. 10s from Bybit to you, you might set a totally wrong time)
=> Still if you are correctly synced, you will encounter this error from time to time (at least I did). Any network delay which is big enough will drive you in this error. So you have to check in your code if this error is present and deal with it by just sending the previous message again.
I think this all is obvious once understood and wish someone would have told me to save hours of time...

**Comment by alishah79** [comment]
> 
> 
> This error cost me hours of time and as others might also encounter it, here what I found: For security, Bybit allows max 5s (min -1s) till a message that was sent from your PC is received by them. => In case your system clock is not in sync with Bybit, you will permanently get this error, because there will be a permanent time diff between the 2 clocks. The error will go away if you sync your system clock to correct time. Alternatively (and better), sync it to the Bybit time. Each request, you get in the return message "time now" back from Bybit, just set this as your time or use the special time endpoint from bybit. (To really ensure no problems, you should only set this time if it does not differ more than e.g. 0.5s from your current time. Otherwise in case of network delay of e.g. 10s from Bybit to you, you might set a totally wrong time) => Still if you are correctly synced, you will encounter this error from time to time (at least I did). Any network delay which is big enough will drive you in this error. So you have to check in your code if this error is present and deal with it by just sending the previous message again. I think this all is obvious once understood and wish someone would have told me to save hours of time...

I just synced my system's clock through win10's settings and it's working.
