### ISSUE TITLE
How do I get only the orderid of a trade from Order.Order_newV2?

### ISSUE THREAD

**Issue by matteotaronna** [bybit-exchange/api-connectors#42]

**Comment by dexter-2** [comment]
You need to parse for the `order_id` value from the response, but this is done with different syntax in different languages.

What language are you using?

**Comment by matteotaronna** [comment]
I'm using python

**Comment by dexter-2** [comment]
Firstly you need to get the response in the form of a *dictionary*. You know it's a dictionary because it has curly brackets `{}`.





`order_creation_dict = client.Order.Order_newV2(side="Buy",symbol="ETHUSD",order_type="Market",qty=1,time_in_force="GoodTillCancel").result()[0]`

Now you can *parse* that dictionary (or dict) for the value you want - in this case, the `order_id`.

`order_id = order_creation_dict["result"]["order_id"]`

Have a look here to learn more: https://www.tutorialspoint.com/python/python_dictionary.htm
